# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NODg9HE6_E0eyf5NRvM5fpmvr2vyo2Z-
"""

import matplotlib.pyplot as plt
import cv2
import numpy as np
from PIL import Image
import random

img1 = plt.imread('cat1.jpg')
img2 = plt.imread('cat2.jpg')
img3 = plt.imread('cat3.jpg')
img4 = plt.imread('dog1.jpg')


print(img1.shape)
print(img2.shape)
print(img3.shape)
print(img4.shape)

dimensions = (224, 224)
new_image1 = cv2.resize(img1, dimensions)
new_image2 = cv2.resize(img2, dimensions)
new_image3 = cv2.resize(img3, dimensions)
new_image4 = cv2.resize(img4, dimensions)

print(new_image1.shape)
cv2.imwrite('cat1.jpg',cv2.cvtColor(new_image1, cv2.COLOR_RGB2BGR))
plt.imshow(new_image1)
plt.show()

plt.title ("cat1.jpg", fontsize = 12)
plt.hist(img1.ravel(), bins = 8)
plt.grid (axis = 'x', alpha = 0.75)
plt.grid (axis = 'y', alpha = 0.75)
plt.xlabel ('Value', fontsize = 12)
plt.ylabel ('Frequency', fontsize = 12)
plt.show()

print(new_image2.shape)
cv2.imwrite('cat2.jpg',cv2.cvtColor(new_image2, cv2.COLOR_RGB2BGR))
plt.imshow(new_image2)
plt.show()

plt.title ("cat2.jpg", fontsize = 12)
plt.hist(img2.ravel(), bins = 8)
plt.grid (axis = 'x', alpha = 0.75)
plt.grid (axis = 'y', alpha = 0.75)
plt.xlabel ('Value', fontsize = 13)
plt.ylabel ('Frequency', fontsize = 13)
plt.show()

print(new_image3.shape)
cv2.imwrite('cat3.jpg',cv2.cvtColor(new_image3, cv2.COLOR_RGB2BGR))
plt.imshow(new_image3)
plt.show()

plt.title ("cat3.jpg", fontsize = 12)
plt.hist(img3.ravel(), bins = 8)
plt.grid (axis = 'x', alpha = 0.75)
plt.grid (axis = 'y', alpha = 0.75)
plt.xlabel ('Value', fontsize = 12)
plt.ylabel ('Frequency', fontsize = 12)
plt.show()

print(new_image4.shape)
cv2.imwrite('dog1.jpg',cv2.cvtColor(new_image4, cv2.COLOR_RGB2BGR))
plt.imshow(new_image4)
plt.show()

plt.title ("dog1.jpg", fontsize = 12)
plt.hist(img4.ravel(), bins = 8)
plt.grid (axis = 'x', alpha = 0.75)
plt.grid (axis = 'y', alpha = 0.75)
plt.xlabel ('Value', fontsize = 12)
plt.ylabel ('Frequency', fontsize = 12)
plt.show()

img1_hsv = cv2.cvtColor(new_image1, cv2.COLOR_BGR2HSV)
img2_hsv = cv2.cvtColor(new_image2, cv2.COLOR_BGR2HSV)
img3_hsv = cv2.cvtColor(new_image3, cv2.COLOR_BGR2HSV)
img4_hsv = cv2.cvtColor(new_image4, cv2.COLOR_BGR2HSV)
 
hist_img1 = cv2.calcHist([img1_hsv], [0,1], None, [180,256], [0,180,0,256])
cv2.normalize(hist_img1, hist_img1, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX);
hist_img2 = cv2.calcHist([img2_hsv], [0,1], None, [180,256], [0,180,0,256])
cv2.normalize(hist_img2, hist_img2, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX);
hist_img3 = cv2.calcHist([img3_hsv], [0,1], None, [180,256], [0,180,0,256])
cv2.normalize(hist_img3, hist_img3, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX);
hist_img4 = cv2.calcHist([img4_hsv], [0,1], None, [180,256], [0,180,0,256])
cv2.normalize(hist_img4, hist_img4, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX);
 
d1 = cv2.compareHist(hist_img1, hist_img4, cv2.HISTCMP_BHATTACHARYYA)
d2 = cv2.compareHist(hist_img2, hist_img4, cv2.HISTCMP_BHATTACHARYYA)
d3 = cv2.compareHist(hist_img3, hist_img4, cv2.HISTCMP_BHATTACHARYYA)

distance_arr =np.array([d1,d2,d3])

for i in range (3): 
  if distance_arr[i]==distance_arr.min():
    if i==0:
      print("cat1.jpg")
    elif i==1:
      print("cat2.jpg")
    else:
      print("cat3.jpg")

begin_row = (random.randint(0,160)) 
begin_col = (random.randint(0,160)) 

final_row, final_col=int(begin_row+64), int(begin_col+64) 

if(0): 
  cropped_img=new_image1[begin_row:final_row , begin_col:final_col] 
if(0): 
  cropped_img=new_image2[begin_row:final_row , begin_col:final_col] 
if(1): 
  cropped_img=new_image3[begin_row:final_row , begin_col:final_col]


cv2.imwrite('cropped_image.jpg', cv2.cvtColor(cropped_img, cv2.COLOR_RGB2BGR))
im1 = Image.open('dog1.jpg')
im2 = Image.open('cropped_image.jpg')

new_row = (random.randint(0,160)) 
new_col = (random.randint(0,160))
im1.paste(im2,(new_row,new_col)) 
display(im1)